name: Terraform Workflow

on:
  push:
    branches:
      - feature/*
    paths:
      - 'dev/**'
      - 'pd/**'
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    strategy:
      matrix:
        environment: [dev, pd]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Terraform Init
        run: terraform init -reconfigure -backend-config=tfbackend
        working-directory: ./${{ matrix.environment }}

      - name: Terraform Plan
        run: terraform plan -var-file=${{ matrix.environment }}.tfvars
        working-directory: ./${{ matrix.environment }}

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    strategy:
      matrix:
        environment: [dev, pd]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Terraform Init
        run: terraform init -reconfigure -backend-config=tfbackend
        working-directory: ./${{ matrix.environment }}

      - name: Terraform Apply
        run: terraform apply -var-file=${{ matrix.environment }}.tfvars -auto-approve
        working-directory: ./${{ matrix.environment }}
