name: Terraform Workflow

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  terraform-plan-dev:
    name: Terraform Plan (dev)
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Terraform Init
        run: terraform init -reconfigure -backend-config=tfbackend
        working-directory: ./dev

      - name: Terraform Plan
        run: terraform plan -var-file=dev.tfvars
        working-directory: ./dev

  terraform-plan-pd:
    name: Terraform Plan (pd)
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Terraform Init
        run: terraform init -reconfigure -backend-config=tfbackend
        working-directory: ./pd

      - name: Terraform Plan
        run: terraform plan -var-file=pd.tfvars
        working-directory: ./pd

  terraform-apply-dev:
    name: Terraform Apply (dev)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Terraform Init
        run: terraform init -reconfigure -backend-config=tfbackend
        working-directory: ./dev

      - name: Terraform Apply
        run: terraform apply -var-file=dev.tfvars -auto-approve
        working-directory: ./dev

  terraform-apply-pd:
    name: Terraform Apply (pd)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Terraform Init
        run: terraform init -reconfigure -backend-config=tfbackend
        working-directory: ./pd

      - name: Terraform Apply
        run: terraform apply -var-file=pd.tfvars -auto-approve
        working-directory: ./pd
